# Documentation https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
notifications:
  commits: commits@trafficserver.apache.org
  issues: issues@trafficserver.apache.org
  pullrequests: github@trafficserver.apache.org
github:
  description: Apache Traffic Server Ingress Controller for Kubernetes
  homepage: https://github.com/apache/trafficserver-ingress-controller
  labels:
    - ingress-controller
    - kubernetes
    - kubernetes-ingress
    - ingress
    - kubernetes-ingress-controller
    - k8s
    - apache
  features:
    issues: true
  enabled_merge_buttons:
    # enable squash button:
    squash: true
