apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: atssnipolicies.trafficserver.apache.org
spec:
  group: trafficserver.apache.org
  names:
    kind: ATSSniPolicy
    plural: atssnipolicies
    singular: atssnipolicy
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                sni:
                  type: array
                  items:
                    type: object
                    properties:
                      fqdn:
                        type: string
                      verify_client:
                        type: string
                        enum: ["NONE", "MODERATE", "STRICT"]
                      verify_client_ca_certs:
                        type: object
                        properties:
                          file:
                            type: string
                          dir:
                            type: string
                      verify_server_policy:
                        type: string
                        enum: ["DISABLED", "PERMISSIVE", "ENFORCED"]
                      verify_server_properties:
                        type: string
                        enum: ["NONE", "SIGNATURE", "NAME", "ALL"]
                      client_cert:
                        type: string
                      client_key:
                        type: string
                      client_sni_policy:
                        type: string
                      ip_allow:
                        type: array
                        items:
                          type: string
                      host_sni_policy:
                        type: string
                        enum: ["DISABLED", "PERMISSIVE", "ENFORCED"]
                      valid_tls_versions_in:
                        type: array
                        items:
                          type: string
                          enum: ["TLSv1", "TLSv1_1", "TLSv1_2", "TLSv1_3"]
                      http2:
                        type: string
                        enum: ["on", "off"]
                      http2_buffer_water_mark:
                        type: integer
                      http2_max_settings_frames_per_minute:
                        type: integer
                      http2_max_ping_frames_per_minute:
                        type: integer
                      http2_max_priority_frames_per_minute:
                        type: integer
                      http2_max_rst_stream_frames_per_minute:
                        type: integer
                      disable_h2:
                        type: boolean
                      tunnel_route:
                        type: string
                      forward_route:
                        type: string
                      partial_blind_route:
                        type: string
                      tunnel_alpn:
                        type: array
                        items:
                          type: string
                     
