apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "ats-ingress.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - ingresses
  - secrets
  - services
  - pods
  - namespaces
  - replicationcontrollers
  - endpoints
  - configmaps
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ats-ingress.fullname" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ats-ingress.fullname" . }}

