name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and push
      run: ./build-master.sh
      env:
        DOCKERHUB_USER: ${{  secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{  secrets.DOCKERHUB_TOKEN }}