name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and push
      run: ./build-master.sh
      # env:
      #   QUAY_USERNAME: ${{  secrets.QUAY_USERNAME }}
      #   QUAY_PASSWORD: ${{  secrets.QUAY_PASSWORD }}