name: Build and Integrate

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.18.3'
          github token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
      
      - name: Build ATS Alpine
        run: docker build -t ats_alpine .
      
      - name: Build Exporter
        run: docker build -t tsexporter k8s/backend/trafficserver_exporter/
      
      - name: Build App 1
        run: docker build -t node-app-1 k8s/backend/node-app-1/
      
      - name: Build App 2
        run: docker build -t node-app-2 k8s/backend/node-app-2/
      
      - name: Install dependencies
        run: |
          cd tests
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test 
        run: |
          cd tests
          pytest -q --minikubeip="$(minikube ip)" suite/test_ingress.py