name: golangci-lint
on:
  push:
    branches:
    - master
    paths-ignore:
    - '.vscode/**'
    - 'charts/**'
    - 'docs/**'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.vscode/**'
    - 'charts/**'
    - 'docs/**'

permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.17.11
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.11
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.46.2
          args: --timeout=10m

