name: Build and Release Helm Chart

on:
  push:
    branches:
    - 'master'
    paths:
    - 'charts/**'

jobs:
  build-and-release-helm:
    if: github.repository == 'apache/trafficserver-ingress-controller'
    runs-on: ubuntu-latest

    steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - uses: actions/checkout@v3
      - run: |
          cd charts
          helm package ats-ingress
          helm repo index . --url https://apache.github.io/trafficserver-ingress-controller
          cp index.yaml ../docs/
          cp ats-ingress-*.tgz ../docs/
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/index.yaml
          git add docs/ats-ingress-*.tgz
          git commit -m 'Release new version of helm chart'
          git push

