name: Test

on:
  push:
    branches:
    - master
    paths-ignore:
    - '.vscode/**'
    - 'charts/**'
    - 'docs/**'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.vscode/**'
    - 'charts/**'
    - 'docs/**'

jobs:

  build:
    name: Test Redis and Lua
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.10
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
   
    # commit for v8.0.0 
    - uses: leafo/gh-actions-lua@ea0ae38722c0b45aa4e770f7c4a650c6b26800d0
      with:
        luaVersion: "5.1.5"
    
    # commit for v4.3.0
    - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5

    - name: Install Busted
      run: |
        luarocks install busted

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test Watcher
      run: go test -v ./watcher/
    
    - name: Test Redis
      run: go test -v ./redis/
    
    - name: Test RedisPluginATS
      run: |
        cd pluginats
        ../.luarocks/bin/busted connect_redis_test.lua
